### ISSUE TITLE
ifconfig not available in confluence image

### ISSUE THREAD

**Issue by ataraxie** [codeclou/docker-atlassian-confluence-data-center#4]
In `docker-entrypoint.sh` of the confluencenode-6.15.3 image there is this line:
`IP_ADDRESS=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')`

It seems to me that `ifconfig` is not installed in the container. At least in my environment I get this:
```
/work-private/docker-entrypoint.sh: line 11: /sbin/ifconfig: No such file or directory
```
I think this container is based on some openjdk container using Ubuntu and I found that `ifconfig` is [not always available](https://serverfault.com/questions/613528/why-isnt-ifconfig-available-in-ubuntu-docker-container).

It works when I build my own image based on yours and add `RUN apt-get update && apt-get -y install net-tools` to my Dockerfile.

**Comment by clouless** [comment]
thanks for the notice. I switched the base image that Might have caused it.
I will rebuild the base image with ifconfig. thx.

6.15.3 is rebuilding just now.
